"use client";

import React, { useState } from "react";
import "./settings.css";

interface TurnkeyDeviceModalProps {
  isOpen: boolean;
  onClose: () => void;
}

function QRCode() {
  const matrix = [
    [1,1,1,1,1,1,1,0,1,0,1,0,1,1,1,1,1,1,1],
    [1,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0,1],
    [1,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,1],
    [1,0,1,1,1,0,1,0,0,0,1,1,1,0,1,1,1,0,1],
    [1,0,1,1,1,0,1,0,1,0,0,0,1,0,1,1,1,0,1],
    [1,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,1],
    [1,1,1,1,1,1,1,0,1,0,1,0,1,1,1,1,1,1,1],
    [0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0],
    [1,1,0,1,1,0,1,1,0,1,1,0,1,0,1,1,0,1,1],
    [0,1,0,0,1,1,0,1,1,0,0,1,0,1,1,0,1,0,0],
    [1,0,1,1,0,0,1,0,0,1,0,0,1,1,0,0,1,0,1],
    [0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,0,1,1,0],
    [1,1,1,1,1,1,1,0,0,0,1,0,1,1,1,0,0,1,0],
    [1,0,0,0,0,0,1,0,1,1,0,1,0,0,0,1,1,0,1],
    [1,0,1,1,1,0,1,0,0,1,1,0,1,0,1,0,0,1,1],
    [1,0,1,1,1,0,1,0,1,0,0,1,0,1,0,1,1,0,0],
    [1,0,1,1,1,0,1,0,0,1,1,0,1,1,0,0,1,0,1],
    [1,0,0,0,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0],
    [1,1,1,1,1,1,1,0,0,0,1,0,1,0,1,0,1,1,1],
  ];

  const cellSize = 6;
  const totalSize = matrix.length * cellSize;

  return (
    <svg width={totalSize} height={totalSize} viewBox={`0 0 ${totalSize} ${totalSize}`} aria-hidden="true" className="turnkey-qr">
      {matrix.map((row, y) =>
        row.map((cell, x) =>
          cell === 1 ? (
            <rect key={`${y}-${x}`} x={x * cellSize} y={y * cellSize} width={cellSize} height={cellSize} fill="#111" />
          ) : null
        )
      )}
    </svg>
  );
}

export default function TurnkeyDeviceModal({ isOpen, onClose }: TurnkeyDeviceModalProps) {
  const [mode, setMode] = useState<"show" | "enter">("show");
  const [deviceName, setDeviceName] = useState("");
  const [showName, setShowName] = useState(false);
  const [pairingCode, setPairingCode] = useState("");

  const autoGeneratedCode = "FERN · 4TWO · MOSS";

  if (!isOpen) return null;

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) onClose();
  };

  return (
    <div className="turnkey-modal-backdrop" onClick={handleBackdropClick}>
      <div className="turnkey-modal" onClick={(e) => e.stopPropagation()}>
        <div className="turnkey-modal-body">
          <div className="turnkey-segmented" role="tablist" aria-label="Device pairing mode">
            <button
              className={`turnkey-segmented-btn ${mode === "show" ? "active" : ""}`}
              onClick={() => setMode("show")}
              type="button"
            >
              Show code
            </button>
            <button
              className={`turnkey-segmented-btn ${mode === "enter" ? "active" : ""}`}
              onClick={() => setMode("enter")}
              type="button"
            >
              Enter code
            </button>
          </div>

          <p className="turnkey-kicker">ADD A DEVICE</p>
          <h2 className="turnkey-title">
            {mode === "show" ? "Add another way in." : "Enter a pairing code."}
          </h2>
          <p className="turnkey-copy">
            {mode === "show" ? (
              <>
                On the device you want to add, open enki.art and choose <strong>Settings → Recovery & 2FA → Add a device</strong>.
                We&apos;ll show you a QR code to scan from this screen.
              </>
            ) : (
              <>
                Paste the code shown on your other device. This adds the current device as another secure way back into your account.
              </>
            )}
          </p>

          <div className="turnkey-panel">
            {mode === "show" ? (
              <div className="turnkey-code-layout">
                <div className="turnkey-qr-frame">
                  <QRCode />
                </div>
                <div className="turnkey-code-copy">
                  <p className="turnkey-code-label">OR PASTE THIS CODE</p>
                  <p className="turnkey-code">{autoGeneratedCode}</p>
                  <p className="turnkey-muted">Expires in 5 minutes.</p>
                </div>
              </div>
            ) : (
              <div className="turnkey-enter-layout">
                <label className="turnkey-code-label" htmlFor="turnkey-pairing-code">
                  CODE FROM OTHER DEVICE
                </label>
                <input
                  id="turnkey-pairing-code"
                  className="turnkey-code-input"
                  type="text"
                  value={pairingCode}
                  onChange={(e) => setPairingCode(e.target.value)}
                  placeholder="FERN · 4TWO · MOSS"
                  autoComplete="one-time-code"
                />
                <p className="turnkey-muted">Use the exact code before it expires.</p>
              </div>
            )}
          </div>

          <div className="turnkey-name-wrap">
            <button className="turnkey-disclosure" onClick={() => setShowName(!showName)} type="button">
              <span>{showName ? "▾" : "▸"}</span>
              Pretend you&apos;ve connected — give it a name
            </button>
            {showName && (
              <input
                className="turnkey-name-input"
                type="text"
                value={deviceName}
                onChange={(e) => setDeviceName(e.target.value)}
                placeholder="e.g. MacBook Pro · Work"
              />
            )}
          </div>
        </div>

        <div className="turnkey-modal-footer">
          <button className="turnkey-footer-btn turnkey-footer-btn-light" onClick={onClose} type="button">
            Cancel
          </button>
          <button className="turnkey-footer-btn turnkey-footer-btn-dark" onClick={onClose} type="button">
            Done — add it
          </button>
        </div>
      </div>
    </div>
  );
}
